from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


PREFERENCES_FILE = "ui_preferences.json"


@dataclass(frozen=True)
class UiPreferences:
    language: str = "de"
    theme: str = "light"
    qso_notifications: bool = True
    last_whats_new_version: str = ""

    def normalized(self) -> "UiPreferences":
        language = self.language if self.language in {"de", "en"} else "de"
        theme = self.theme if self.theme in {"light", "dark"} else "light"
        return UiPreferences(
            language=language,
            theme=theme,
            qso_notifications=bool(self.qso_notifications),
            last_whats_new_version=str(self.last_whats_new_version or "").strip(),
        )


PALETTES = {
    "light": {
        "BG": "#f6f8fb", "CARD": "#ffffff", "TEXT": "#172033", "MUTED": "#667085",
        "ACCENT": "#0969da", "ACCENT_DARK": "#0556b3", "BORDER": "#d8dee8",
        "OK": "#1a8f36", "WARN": "#9a6700", "ERR": "#b42318", "SIDEBAR": "#ffffff",
        "SIDEBAR_TEXT": "#253044", "ACTIVE_BG": "#eaf2ff", "SURFACE": "#f8fbff",
        "INPUT_BG": "#ffffff", "PHOTO_BG": "#f3f6fa", "NEUTRAL_BADGE_BG": "#edf2f7",
        "OK_BADGE_BG": "#e9f7ec", "WARN_BADGE_BG": "#fff4df", "NAV_HOVER": "#f1f5fb",
        "NAV_ACTIVE_HOVER": "#dceaff", "PROGRESS_BG": "#e9eef3", "DISABLED": "#9bb8cf",
    },
    "dark": {
        "BG": "#0f141c", "CARD": "#171e29", "TEXT": "#e8edf5", "MUTED": "#9aa6b5",
        "ACCENT": "#58a6ff", "ACCENT_DARK": "#79b8ff", "BORDER": "#303b4a",
        "OK": "#3fb950", "WARN": "#d29922", "ERR": "#f85149", "SIDEBAR": "#121923",
        "SIDEBAR_TEXT": "#dce6f3", "ACTIVE_BG": "#1f3552", "SURFACE": "#182231",
        "INPUT_BG": "#202938", "PHOTO_BG": "#202938", "NEUTRAL_BADGE_BG": "#273244",
        "OK_BADGE_BG": "#183b25", "WARN_BADGE_BG": "#453515", "NAV_HOVER": "#1a2635",
        "NAV_ACTIVE_HOVER": "#29476b", "PROGRESS_BG": "#273244", "DISABLED": "#526277",
    },
}


def load_ui_preferences(data_dir: Path) -> UiPreferences:
    path = Path(data_dir) / PREFERENCES_FILE
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            return UiPreferences()
        return UiPreferences(
            language=str(payload.get("language", "de")),
            theme=str(payload.get("theme", "light")),
            qso_notifications=bool(payload.get("qso_notifications", True)),
            last_whats_new_version=str(payload.get("last_whats_new_version", "")),
        ).normalized()
    except (OSError, ValueError, TypeError):
        return UiPreferences()


def save_ui_preferences(data_dir: Path, preferences: UiPreferences) -> None:
    data_dir = Path(data_dir)
    data_dir.mkdir(parents=True, exist_ok=True)
    path = data_dir / PREFERENCES_FILE
    temporary = path.with_suffix(path.suffix + ".tmp")
    normalized = preferences.normalized()
    temporary.write_text(
        json.dumps({
            "language": normalized.language,
            "theme": normalized.theme,
            "qso_notifications": normalized.qso_notifications,
            "last_whats_new_version": normalized.last_whats_new_version,
        }, indent=2) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


# Static widget texts and frequently changing status messages are translated at
# the presentation boundary. Internal values (ADIF modes, database keys and
# profile data) intentionally remain language-neutral/backwards compatible.
ENGLISH = {
    "Logbuch": "Logbook", "Logbuch & Sync": "Logbook & Sync", "Statistiken": "Statistics",
    "Einstellungen": "Settings", "QSO loggen": "Log QSO", "Gegenstation": "Contact station",
    "Frequenz (MHz)": "Frequency (MHz)", "Frequenz": "Frequency", "Leistung (W)": "Power (W)",
    "RST gesendet": "RST sent", "RST empfangen": "RST received",
    "Locator Gegenstation": "Contact grid locator", "QTH Gegenstation": "Contact QTH",
    "POTA Ref Gegenstation": "Contact POTA ref", "SOTA Ref Gegenstation": "Contact SOTA ref",
    "WWFF Ref Gegenstation": "Contact WWFF ref", "Kommentar": "Comment", "Notizen": "Notes",
    "QSO speichern": "Save QSO", "Speichern + Neu": "Save + New", "Felder leeren": "Clear fields",
    "DX-Spot senden": "Send DX spot", "Datum / Zeit": "Date / Time", "Datum": "Date", "Uhrzeit": "Time",
    "Lokal": "Local", "Callbook-Informationen": "Callbook information", "Kein Foto geladen": "No photo loaded",
    "Entfernung": "Distance", "Peilung": "Bearing",
    "Rufzeichen eingeben …": "Enter callsign …", "Callbook neu laden": "Reload callbook",
    "DXCC · offline": "DXCC · offline", "Land / DXCC": "Country / DXCC", "Kontinent": "Continent",
    "Bereit": "Ready", "Verwalten": "Manage", "PROFIL": "PROFILE",
    "Fast Log / DXpedition": "Fast Log / DXpedition", "Contest Logging": "Contest Logging",
    "DX Cluster": "DX Cluster", "CAT Setup": "CAT Setup", "UDP Logging": "UDP Logging",
    "Station & Wavelog": "Station & Wavelog", "Callbook & Online-Dienste": "Callbook & Online services",
    "Daten & Verbindungen": "Data & connections", "Allgemein": "General",
    "Sprache": "Language", "Darstellung": "Appearance", "Theme": "Theme",
    "Hell / Light": "Light", "Dunkel / Dark": "Dark",
    "App-weite Einstellungen": "App-wide settings", "Deutsch": "German", "English": "English",
    "Systemhinweis nach gespeichertem QSO": "System notification after a saved QSO",
    "Offline-Stationsprofil": "Offline station profile", "Operator-Rufzeichen": "Operator callsign",
    "Stationsrufzeichen": "Station callsign", "Eigener Locator": "Own grid locator", "QTH / Ort": "QTH / location",
    "Standardleistung (W)": "Default power (W)", "Aktuelle Aktivierung (optional)": "Current activation (optional)",
    "POTA-Referenz": "POTA reference", "SOTA-Referenz": "SOTA reference", "WWFF-Referenz": "WWFF reference",
    "Wavelog URL": "Wavelog URL", "API-v2 Token": "API v2 token",
    "Verbindung testen & Profile laden": "Test connection & load profiles",
    "Wavelog-Stationsprofil": "Wavelog station profile",
    "Dieses Logger-Profil synchronisiert ausschließlich QSOs des ausgewählten Wavelog-Stationsprofils.": "This logger profile synchronizes only QSOs from the selected Wavelog station profile.",
    "Werte aus Wavelog-Profil übernehmen": "Use values from Wavelog profile",
    "Rufzeichen-Lookup": "Callsign lookup", "Datenquelle": "Data source",
    "Bei vollständigem Rufzeichen automatisch abfragen": "Look up complete callsigns automatically",
    "Direkter QRZ.com-Zugang": "Direct QRZ.com access", "QRZ.com Benutzername": "QRZ.com username",
    "QRZ.com Passwort": "QRZ.com password", "Callbook-Verbindung testen": "Test callbook connection",
    "QRZ.com wird bei direkter Auswahl unabhängig von Wavelog abgefragt. Benutzername und Passwort sind dann erforderlich.": "When selected directly, QRZ.com is queried independently of Wavelog. Username and password are then required.",
    "eQSL.cc Benutzername": "eQSL.cc username", "eQSL.cc Passwort": "eQSL.cc password",
    "Lokale Logdateien": "Local log files", "DX-Spotter-Verbindung": "DX spotter connection",
    "DXSpider-Host zum Spotten": "DXSpider host for spotting", "Telnet-Port": "Telnet port",
    "Login-Rufzeichen aus Logbuch": "Login callsign from logbook",
    "Einstellungen speichern": "Save settings", "Daten & Backup": "Data & backup",
    "Was ist neu?": "What's new?", "Backup erstellen": "Create backup",
    "Backup wiederherstellen": "Restore backup", "Noch kein Backup in dieser Sitzung erstellt.": "No backup created in this session yet.",
    "Vollständiges Changelog": "Full changelog", "Loslegen": "Get started",
    "DX-Spot senden": "Send DX spot", "Letztes QSO spotten": "Spot last QSO",
    "CAT-Einstellungen speichern": "Save CAT settings", "CAT starten": "Start CAT", "CAT stoppen": "Stop CAT",
    "Verbindung testen": "Test connection", "Funkgerät": "Radio", "Hersteller / Modell": "Manufacturer / model",
    "Geräte-Port": "Device port", "Baudrate": "Baud rate", "Datenbits": "Data bits",
    "Stoppbits": "Stop bits", "Parität": "Parity", "Handshake": "Handshake",
    "Abfrageintervall (ms)": "Polling interval (ms)", "Lokaler rigctld-Port": "Local rigctld port",
    "Telnet-Verbindung": "Telnet connection", "DX-Cluster-Host": "DX cluster host",
    "Login-Rufzeichen": "Login callsign", "Verbinden": "Connect", "Trennen": "Disconnect",
    "Spot-Filter": "Spot filters", "Zeitraum": "Time range", "Spotter-Region": "Spotter region",
    "Liste leeren": "Clear list", "Empfangene DX-Spots": "Received DX spots",
    "QSO übernehmen": "Use for QSO", "Alle": "All", "Europa": "Europe", "Nordamerika": "North America",
    "Südamerika": "South America", "Asien/Pazifik": "Asia/Pacific", "Afrika": "Africa", "Unbekannt": "Unknown",
    "15 Minuten": "15 minutes", "30 Minuten": "30 minutes", "60 Minuten": "60 minutes", "2 Stunden": "2 hours",
    "Gesamt": "All time", "Dieses Jahr": "This year", "Dieser Monat": "This month",
    "Diese Woche": "This week", "Heute (UTC)": "Today (UTC)", "Alle Operatoren": "All operators",
    "Noch keine Daten": "No data yet", "Aktivitäten": "Activities", "Offene Sync-Themen": "Open sync issues",
    "Starten": "Start", "Stoppen": "Stop", "Speichern": "Save", "Abbrechen": "Cancel", "Schließen": "Close",
    "Löschen": "Delete", "Bearbeiten": "Edit", "Aktualisieren": "Refresh", "Exportieren": "Export",
    "Importieren": "Import", "Ja": "Yes", "Nein": "No", "Deaktiviert": "Disabled",
    "Über Wavelog (empfohlen)": "Via Wavelog (recommended)", "Direkt über QRZ.com": "Directly via QRZ.com",
    "COMING SOON": "COMING SOON", "Coming soon – derzeit noch ohne Funktion.": "Coming soon – not active yet.",
    "TUNE (ATU)": "TUNE (ATU)", "TUNE läuft …": "TUNE running …", "Tuner starten": "Start tuner",
    "CAT ist nicht gestartet": "CAT is not running", "Antennentuner wird gestartet …": "Starting antenna tuner …",
    "Antennentuner gestartet": "Antenna tuner started",
    "Antennentuner konnte nicht gestartet werden": "Antenna tuner could not be started",
    "●  WAVELOG ONLINE": "●  WAVELOG ONLINE", "Verbunden · neuer QSO-Push aktiv": "Connected · new-QSO push active",
    "Verbunden · manueller Sync": "Connected · manual sync", "Wavelog nicht eingerichtet.": "Wavelog is not configured.",
    "Offline · QSOs bleiben lokal.": "Offline · QSOs remain local.",
    "Online-Modus: neue QSOs automatisch zu Wavelog pushen": "Online mode: automatically push new QSOs to Wavelog",
    "Vollständigen Sync beim App-Start ausführen": "Run a full sync when the app starts",
    "Vollständigen Sync beim Beenden ausführen": "Run a full sync when the app closes",
    "Alle Optionen gelten pro Profil und sind unabhängig wählbar. Offline werden QSOs weiter sicher lokal gespeichert.": "All options are profile-specific and can be selected independently. QSOs remain safely stored locally while offline.",
    "Wavelog-Status wird geprüft.": "Checking Wavelog status.",
    "Neue LOCAL ONLY QSOs werden zu Wavelog hochgeladen …": "Uploading new LOCAL ONLY QSOs to Wavelog …",
    "Online-Push fehlgeschlagen · QSOs bleiben lokal": "Online push failed · QSOs remain local",
    "Vollständiger Start-Sync läuft …": "Full startup sync running …",
    "Vollständiger Abschluss-Sync läuft …": "Full shutdown sync running …",
    "Beenden wartet auf die laufende Wavelog-Übertragung …": "Closing waits for the active Wavelog transfer …",
    "Wavelog-Synchronisierung": "Wavelog synchronization",
    "Wavelog wird synchronisiert": "Synchronizing Wavelog",
    "Vor der Bedienung wird das aktive Profil vollständig mit Wavelog abgeglichen.": "The active profile is fully synchronized with Wavelog before the app can be used.",
    "Vor dem Beenden wird das aktive Profil vollständig mit Wavelog abgeglichen.": "The active profile is fully synchronized with Wavelog before the app closes.",
    "Synchronisierung abgeschlossen": "Synchronization completed",
    "Synchronisierung fehlgeschlagen": "Synchronization failed",
    "Die App wird nach OK geschlossen.": "The app will close after you select OK.",
    "Nach OK kann die App verwendet werden.": "The app can be used after you select OK.",
    "Wavelog konnte nicht vollständig synchronisiert werden. Die lokalen QSOs bleiben sicher gespeichert.": "Wavelog could not be fully synchronized. The local QSOs remain safely stored.",
    "Automatische Synchronisierung läuft …": "Automatic synchronization running …",
    "Wavelog ist wieder erreichbar · Online-Modus aktiv": "Wavelog is reachable again · Online mode active",
    "Wavelog nicht erreichbar · LOCAL ONLY": "Wavelog is unavailable · LOCAL ONLY",
    "Auto-Sync fehlgeschlagen · QSOs bleiben LOCAL ONLY": "Auto-sync failed · QSOs remain LOCAL ONLY",
    "Auswertung": "Analysis", "Bänder": "Bands", "Operator:": "Operator:", "Top Calls": "Top calls",
    "Top Länder / DXCC": "Top countries / DXCC", "QSOs nach Band": "QSOs by band",
    "QSOs nach Mode": "QSOs by mode", "QSOs nach Operator": "QSOs by operator",
    "ADI-Ordner öffnen": "Open ADI folder", "Aktivieren": "Enable", "Andere Logprogramme": "Other logging programs",
    "Bind-Adresse": "Bind address", "CAT-/COM-Schnittstelle": "CAT / COM interface", "CAT-Status": "CAT status",
    "Contest-Preset": "Contest preset", "Contest-QSO loggen": "Log contest QSO", "Contest-Session": "Contest session",
    "Mit Wavelog abgleichen": "Sync with Wavelog", "ADIF Contest-ID": "ADIF contest ID",
    "Contest (ADIF-Name)": "Contest (ADIF name)", "Standardband": "Default band",
    "Start UTC": "Start UTC", "Ende UTC": "End UTC", "Kommentar": "Comment",
    "Start-Seriennummer": "Starting serial number", "Gesendeter Text-Exchange": "Sent text exchange",
    "Standardfrequenz (MHz)": "Default frequency (MHz)", "Standard-RST": "Default RST",
    "Duplizieren": "Duplicate", "Einrichtung in WSJT-X": "Setup in WSJT-X", "Erweitert": "Advanced",
    "Exchange-Felder": "Exchange fields", "Feste QSO-Daten": "Fixed QSO data",
    "Funkgerät & Schnittstelle": "Radio & interface", "Funkgerät suchen": "Find radio",
    "Hamlib wird geprüft …": "Checking Hamlib …", "Hamlib-Funkgerät": "Hamlib radio",
    "Interne Hamlib-Steuerung": "Bundled Hamlib control", "Keine Online-Daten verfügbar.": "No online data available.",
    "Keine Session": "No session", "Letzte Contest-QSOs": "Latest contest QSOs",
    "Letztes QSO zurücknehmen": "Undo last QSO", "Lokale Version erzwingen": "Use local version",
    "Neu": "New", "Neu laden": "Reload", "Noch kein Contest-Preset angelegt": "No contest preset yet",
    "Noch kein QSO empfangen.": "No QSO received yet.", "Nur Rufzeichen + Enter": "Callsign + Enter only",
    "Pileup-Eingabe": "Pileup entry", "Profil lokal löschen": "Delete local profile",
    "QSO bearbeiten": "Edit QSO", "QSO lokal speichern": "Save QSO locally", "QSO löschen": "Delete QSO",
    "QSOs dieser Fast-Log-Sitzung": "QSOs in this Fast Log session", "Serielle Parameter": "Serial parameters",
    "Seriennummer": "Serial number", "Session beenden": "End session", "Session starten": "Start session",
    "Speicherung": "Storage", "Standardband / Mode": "Default band / mode", "Synchronisieren": "Synchronize",
    "UDP Logging beim App-Start automatisch starten": "Start UDP logging automatically when the app starts",
    "UDP Logging beim App-Start und Profilwechsel automatisch starten": "Start UDP logging automatically at app startup and profile changes",
    "WSJT-X Live: kein aktives QSO.": "WSJT-X Live: no active QSO.",
    "UDP starten": "Start UDP", "UDP stoppen": "Stop UDP", "UDP-Empfänger": "UDP receiver",
    "UDP-Port": "UDP port", "UDP-Status": "UDP status", "Umbenennen": "Rename",
    "Wavelog-Version übernehmen": "Use Wavelog version", "Werte aus QSO/CAT": "Values from QSO/CAT",
    "Sync-Details": "Sync details", "Keine offenen Sync-Details.": "No open sync details.",
    "QSO auswählen, um Sync-Details anzuzeigen.": "Select a QSO to display sync details.",
    "SYNC-FEHLER: ": "SYNC ERROR: ", "KONFLIKT: ": "CONFLICT: ",
    "Lokale und Wavelog-Version wurden seit dem letzten gemeinsamen Stand geändert.": "The local and Wavelog versions were both changed since the last shared state.",
    "Das QSO wurde in Wavelog gelöscht, lokal aber anschließend verändert.": "The QSO was deleted in Wavelog but was changed locally afterwards.",
    "Projekt unterstützen": "Support my work", "Buy Me a Coffee": "Buy Me a Coffee",
    "Datum UTC": "Date UTC", "Zeit": "Time", "DX-Rufzeichen": "DX callsign", "DX-Land": "DX country",
    "Spotter-Land": "Spotter country",
    "Rufzeichen": "Callsign", "Zeit UTC HHMMSS": "Time UTC HHMMSS", "Frequenz MHz": "Frequency MHz",
    "Locator": "Grid locator", "Leistung W": "Power W", "POTA Ref": "POTA ref", "SOTA Ref": "SOTA ref",
    "WWFF Ref": "WWFF ref",
    "Profil wechseln": "Switch profile", "Profil anlegen": "Create profile", "Profil umbenennen": "Rename profile",
    "Profil löschen": "Delete profile", "Profil gelöscht": "Profile deleted", "Name des neuen Profils:": "Name of the new profile:",
    "Name für das duplizierte Profil:": "Name for the duplicated profile:", "Neuer Profilname:": "New profile name:",
    "Bearbeiten fehlgeschlagen": "Editing failed", "Konflikt": "Conflict",
    "Stationsdaten sind profilspezifisch; Sprache und Theme gelten app-weit.": "Station data is profile-specific; language and theme apply app-wide.",
    "Backup und Wiederherstellung der Profile, Einstellungen und ADI-Logbücher werden hier ergänzt.": "Profile, settings and ADI logbook backup and restore will be added here.",
    "Diese Daten werden in deine ADI-Dateien geschrieben und funktionieren auch komplett ohne Internet.": "These values are written to your ADI files and work completely offline.",
    "Die Aktivierungsreferenzen werden automatisch als MY_* Felder in jedes neue QSO geschrieben.": "Activation references are written to every new QSO as MY_* fields.",
    "Name, Locator, QTH und – falls vorhanden – das Stationsfoto werden beim Tippen geladen. Ohne Internet läuft das Logging still weiter.": "Name, grid locator, QTH and, if available, the station photo are loaded while typing. Logging continues silently without internet.",
    "QRZ.com wird bei direkter Auswahl unabhängig von Wavelog abgefragt. Benutzername und Passwort sind dann erforderlich. QRZ kann ein XML-Abonnement voraussetzen.": "When selected directly, QRZ.com is queried independently of Wavelog. Username and password are then required. QRZ may require an XML subscription.",
    "Die Zugangsdaten können bereits profilspezifisch hinterlegt werden. Derzeit findet noch keine Verbindung, kein Download und kein Upload statt.": "Credentials can already be stored per profile. No connection, download or upload is active yet.",
    "ADI bleibt das primäre Logbuchformat. Die SQLite-Datei enthält nur Einstellungen, Sync-Metadaten und den Callbook-Cache.": "ADI remains the primary logbook format. SQLite contains only settings, sync metadata and the callbook cache.",
    "Doppelklick stimmt den TRX auf Frequenz und Mode ab. QSO übernehmen füllt anschließend das Formular.": "Double-click tunes the radio to frequency and mode. Use for QSO then fills the form.",
    "Überschriften sortieren · neu: hellblau · gleicher Mode gearbeitet: grün · Doppelklick stimmt TRX ab.": "Sort by headings · new: light blue · worked in the same mode: green · double-click tunes the radio.",
    "Fotoformat in dieser Laufzeit nicht verfügbar": "Photo format is not available in this runtime",
    "Hamlib ist nicht verfügbar.": "Hamlib is not available.",
    "Automatische Abfrage ist deaktiviert.": "Automatic lookup is disabled.",
    "Callbook wird abgefragt …": "Looking up callsign …", "Callbook-Abfrage ist deaktiviert.": "Callbook lookup is disabled.",
    "Spotter-Verbindung ist getrennt.": "Spotter connection is closed.",
    "Spotter-Verbindung wird erst beim Senden aufgebaut.": "The spotter connection is opened when sending.",
    "DX Cluster ist getrennt.": "DX Cluster is disconnected.",
    "DX Cluster ist getrennt · zum Empfangen bitte manuell verbinden.": "DX Cluster is disconnected · connect manually to receive spots.",
    "UDP-Logging ist ausgeschaltet.": "UDP logging is off.",
    "UDP-Logging ist ausgeschaltet · zum Empfangen bitte UDP starten.": "UDP logging is off · start UDP to receive QSOs.",
    "Mit Wavelog verbinden & synchronisieren": "Connect and synchronize with Wavelog",
    "Wavelog verbinden": "Connect Wavelog", "Aktivierung beenden": "End activation", "Beenden": "End",
    "Aktuellen Standort verwenden": "Use current location", "GPS übernehmen": "Use GPS",
    "Standortdaten online ergänzen": "Complete location online", "Standort ergänzen": "Complete location",
    "Mögliche Referenzen suchen": "Find possible references", "Referenzen suchen": "Find references",
    "Aktivierung starten": "Start activation", "Starten": "Start",
    "Ausgewählte Treffer übernehmen": "Use selected matches", "Treffer übernehmen": "Use matches",
    "POTA-Grenze prüfen": "Check POTA boundary", "POTA-Map": "POTA map",
    "Referenzdaten aktualisieren": "Update reference data", "Daten aktualisieren": "Update data",
    "Ausgewählte Aktivierung wiederholen": "Repeat selected activation",
    "Aktivierung wiederholen": "Repeat activation",
    "Mögliche Referenzen · Mehrfachauswahl mit Strg/Shift": "Possible references · multi-select with Ctrl/Shift",
    "Mögliche Referenzen · Strg/Shift": "Possible references · Ctrl/Shift",
}

# Dialogs, confirmations and less frequently visited pages must be just as
# complete as the main navigation.  Keeping these exact strings here also
# makes messagebox translations deterministic (dynamic suffixes are handled
# by PHRASES below).
ENGLISH.update({
    "ADI-Logbuch zusammengeführt": "ADI logbook merged",
    "Für diese Version liegen keine Versionshinweise vor.": "No release notes are available for this version.",
    "Die wichtigsten Neuerungen auf einen Blick:": "The most important changes at a glance:",
    "Update verfügbar": "Update available",
    "Für dieses System wurde kein passendes Update-Paket gefunden. Möchtest du die Downloadseite öffnen?": "No suitable update package was found for this system. Do you want to open the download page?",
    "Kein automatisches Paket gefunden": "No automatic package found",
    "Update wird vorbereitet": "Preparing update",
    "Prüfsumme wird geladen …": "Loading checksum …",
    "Update fehlgeschlagen": "Update failed",
    "Update geprüft": "Update checked",
    "Während einer Synchronisierung kann das Profil nicht gewechselt werden.": "The profile cannot be changed while synchronization is running.",
    "Im QSO-Formular stehen noch Eingaben. Beim Profilwechsel wird das Formular geleert.\n\nTrotzdem wechseln?": "The QSO form still contains data. Switching profiles will clear the form.\n\nSwitch anyway?",
    "Bitte zuerst auf ein anderes Profil wechseln und dieses Profil dann löschen.": "Switch to another profile before deleting this profile.",
    "QSO konnte nicht gespeichert werden": "QSO could not be saved",
    "Band, Mode, Frequenz und Rapporte einmal festlegen. Danach genügt: Rufzeichen eingeben und Enter. Jedes QSO wird sofort lokal in ADI gespeichert; Wavelog wird erst über den manuellen Sync angesprochen.": "Set band, mode, frequency and reports once. Then just enter a callsign and press Enter. Every QSO is immediately stored locally in ADI; Wavelog is contacted only by manual sync.",
    "Fast Log: aktuelle QSO-/CAT-Werte übernommen": "Fast Log: current QSO/CAT values applied",
    "Fast-Log-QSO konnte nicht gespeichert werden": "Fast Log QSO could not be saved",
    "In dieser Sitzung wurde noch kein QSO gespeichert.": "No QSO has been saved in this session yet.",
    "Dieses QSO ist nicht mehr ausschließlich lokal und kann hier nicht zurückgenommen werden.": "This QSO is no longer local-only and cannot be undone here.",
    "Letztes Fast-Log-QSO zurücknehmen": "Undo last Fast Log QSO",
    "Bitte zuerst ein Contest-Preset auswählen.": "Select a contest preset first.",
    "Dieses Preset wird von der laufenden Session benutzt. Bitte Session zuerst beenden.": "This preset is used by the active session. End the session first.",
    "Contest-Preset löschen": "Delete contest preset",
    "Bitte zuerst ein Contest-Preset anlegen/auswählen.": "Create or select a contest preset first.",
    "Es läuft bereits eine Contest-Session.": "A contest session is already running.",
    "Bitte das Preset bearbeiten und einen ADIF-Namen wie DARC-WAG oder DARC-FT4 eintragen. Eine numerische Wavelog-ID ist hier nicht gültig.": "Edit the preset and enter an ADIF name such as DARC-WAG or DARC-FT4. A numeric Wavelog ID is not valid here.",
    "Station und Operator müssen gesetzt sein.": "Station and operator must be set.",
    "Es läuft keine Contest-Session.": "No contest session is running.",
    "Bitte zuerst die Contest-Session starten.": "Start the contest session first.",
    "Das aktive Preset passt nicht zur laufenden Session.": "The active preset does not match the running session.",
    "Contest-QSO konnte nicht gespeichert werden": "Contest QSO could not be saved",
    "Keine Aktivierung aktiv": "No active activation",
    "Neue xOTA-Aktivierung": "New xOTA activation",
    "GPS, Internet und Referenzdienste sind optional. Alle Werte bleiben editierbar.": "GPS, internet and reference services are optional. All values remain editable.",
    "Bestätigte Referenzen (mehrere mit Komma)": "Confirmed references (separate multiple values with commas)",
    "Letzte Aktivierungen": "Recent activations",
    "Betriebssystem-Standort wird abgefragt …": "Requesting operating-system location …",
    "Bitte gültige Koordinaten eintragen.": "Enter valid coordinates.",
    "Standortdaten werden online ergänzt …": "Completing location data online …",
    "Standortdaten ergänzt · © OpenStreetMap contributors": "Location data completed · © OpenStreetMap contributors",
    "Lokale und verfügbare Online-Referenzen werden gesucht …": "Searching local and available online references …",
    "Referenzen übernehmen": "Use references",
    "xOTA-Referenzdaten werden aktualisiert …": "Updating xOTA reference data …",
    "xOTA-Aktivierung": "xOTA activation",
    "Es läuft keine Aktivierung.": "No activation is running.",
    "xOTA beenden": "End xOTA activation",
    "Keine xOTA-Aktivierung aktiv": "No active xOTA activation",
    "Offline-Logging ist jederzeit möglich.": "Offline logging is always available.",
    "Bitte eine aktive oder gespeicherte Aktivierung auswählen.": "Select an active or saved activation.",
    "Name der neuen Station Location:": "Name of the new station location:",
    "QSL-Status: ✓ bestätigt · ↑ gesendet/hochgeladen · … wartet · — kein Status · ? nicht verfügbar": "QSL status: ✓ confirmed · ↑ sent/uploaded · … queued · — no status · ? unavailable",
    "Die Datei wird geprüft und mit dem lokalen Profil-Logbuch zusammengeführt. Dubletten werden übersprungen und vorher wird automatisch ein ZIP-Backup erzeugt.\n\nFortfahren?": "The file will be validated and merged into the local profile logbook. Duplicates are skipped and a ZIP backup is created automatically first.\n\nContinue?",
    "ADIF-Import fehlgeschlagen": "ADIF import failed",
    "ADIF-Export fehlgeschlagen": "ADIF export failed",
    "QSO lokal gelöscht": "QSO deleted locally",
    "Sync fehlgeschlagen": "Sync failed",
    "Das ausgewählte QSO hat keinen Sync-Konflikt.": "The selected QSO has no sync conflict.",
    "Konflikt konnte nicht aufgelöst werden": "Conflict could not be resolved",
    "Ordner öffnen": "Open folder",
    "CAT-Einstellungen gehören zum aktiven Logger-Profil. Hamlib wird von der Anwendung selbst verwaltet.": "CAT settings belong to the active logger profile. Hamlib is managed by the application.",
    "CAT wird nach jedem Programmstart bewusst manuell gestartet.": "CAT is deliberately started manually after each application start.",
    "Frequenz und der vom Funkgerät gemeldete Modus werden automatisch in normales und Contest-Logging übernommen. Digitale Betriebsarten wie FT8 kann CAT allein nicht sicher erkennen; ein bereits gewählter Digitalmodus bleibt deshalb erhalten.": "Frequency and the mode reported by the radio are applied automatically to normal and contest logging. CAT alone cannot reliably identify digital modes such as FT8, so an already selected digital mode is preserved.",
    "CAT ist nicht gestartet. Bitte zuerst im CAT Setup verbinden.": "CAT is not running. Connect in CAT Setup first.",
    "Der automatische Tuner des Funkgeräts wird gestartet. Das Funkgerät kann dabei kurz senden.\n\nAntenne und Leistungsgrenzen geprüft – TUNE jetzt ausführen?": "The radio's automatic tuner will start. The radio may transmit briefly.\n\nAntenna and power limits checked — run TUNE now?",
    "CAT-Verbindung": "CAT connection",
    "CAT-Test läuft …": "Testing CAT …",
    "Online-Funktion: Der Empfang funktioniert nur bei bestehender Internetverbindung. Host und Port gehören zum aktiven Profil; das Login-Rufzeichen kommt immer aus dessen Stationsdaten. Die Empfangsverbindung wird nach jedem Programmstart bewusst manuell hergestellt.": "Online feature: reception requires an internet connection. Host and port belong to the active profile; the login callsign always comes from its station data. The receive connection is deliberately established manually after each application start.",
    "DX-Cluster-Verbindung beendet": "DX Cluster connection closed",
    "Bitte zuerst einen DX-Spot auswählen.": "Select a DX spot first.",
    "Zum Abstimmen des TRX bitte zuerst CAT im CAT Setup starten.": "Start CAT in CAT Setup before tuning the radio.",
    "Bitte Rufzeichen und eine gültige Frequenz im QSO-Formular eintragen.": "Enter a callsign and valid frequency in the QSO form.",
    "Optionaler Kommentar für den öffentlichen DX-Spot:": "Optional comment for the public DX spot:",
    "DX-Spot öffentlich senden": "Send public DX spot",
    "DX-Spot konnte nicht gesendet werden": "DX spot could not be sent",
    "Empfängt den laufenden QSO-Status und geloggte QSOs aus WSJT-X oder anderen Programmen. Die Einstellungen gehören zum aktiven Logger-Profil.": "Receives live QSO status and logged QSOs from WSJT-X or other programs. The settings belong to the active logger profile.",
    "127.0.0.1 nimmt nur Programme auf diesem PC an. 0.0.0.0 erlaubt auch Pakete aus dem lokalen Netzwerk.": "127.0.0.1 accepts only programs on this computer. 0.0.0.0 also accepts packets from the local network.",
    "Der Port ist frei wählbar. Er muss in Sender und Logger identisch und auf diesem PC noch frei sein.": "The port is freely selectable. It must match in sender and logger and still be available on this computer.",
    "Programme, die einen vollständigen ADIF-Datensatz mit <EOR> per UDP senden, können denselben Empfänger verwenden. Andere Protokolle wie N1MM-XML brauchen einen eigenen Adapter.": "Programs that send a complete ADIF record with <EOR> over UDP can use the same receiver. Other protocols such as N1MM XML require a separate adapter.",
    "UDP Logging konnte nicht gestartet werden": "UDP logging could not be started",
    "Logger-Backup speichern": "Save logger backup",
    "Backup wird erstellt …": "Creating backup …",
    "Backup fehlgeschlagen": "Backup failed",
    "Logger-Backup auswählen": "Select logger backup",
    "Backup ungültig": "Invalid backup",
    "Backup wird wiederhergestellt": "Restoring backup",
    "Sicherheitsbackup wird erstellt …": "Creating safety backup …",
    "Daten werden sicher wiederhergestellt …": "Restoring data safely …",
    "Wiederherstellung fehlgeschlagen": "Restore failed",
    "API v2 (wl2_… Token). Manueller Sync bleibt immer möglich; optional wechselt die App automatisch in den Online-Modus. Für Callbook-Daten wird zusätzlich lookup:read benötigt.": "API v2 (wl2_… token). Manual sync always remains available; optionally the app switches to online mode automatically. Callbook data additionally requires lookup:read.",
    "POTA, SOTA und WWFF verwenden die eingebauten Quellen. Für IOTA und COTA/WCA kann optional eine eigene CSV-URL hinterlegt werden; ohne Quelle bleibt die manuelle Eingabe verfügbar.": "POTA, SOTA and WWFF use built-in sources. An optional custom CSV URL can be configured for IOTA and COTA/WCA; manual entry remains available without a source.",
    "Getrennt vom reinen Empfangs-Cluster. Beim öffentlichen Spotten wird diese DXSpider-Verbindung automatisch aufgebaut. Sie benötigt Internet; ohne Verbindung wird nichts gesendet. Das Login-Rufzeichen kommt immer aus dem aktiven Stationsprofil.": "Separate from the receive-only cluster. This DXSpider connection is established automatically when sending a public spot. It requires internet; nothing is sent without a connection. The login callsign always comes from the active station profile.",
    "Bitte zuerst ein gültiges Operator- oder Stationsrufzeichen eintragen.": "Enter a valid operator or station callsign first.",
    "Bitte zuerst die Verbindung testen und ein Stationsprofil auswählen.": "Test the connection and select a station profile first.",
    "Wavelog-Profil": "Wavelog profile",
    "Stationswerte aus Wavelog übernommen · noch nicht gespeichert": "Station values imported from Wavelog · not saved yet",
    "Gelöscht werden die lokalen Einstellungen und Sync-Metadaten dieses Logger-Profils.": "The local settings and sync metadata of this logger profile will be deleted.",
    "Wavelog wird NICHT verändert. Es werden weder QSOs noch Stationsprofile in Wavelog gelöscht.": "Wavelog will NOT be changed. Neither QSOs nor station profiles will be deleted from Wavelog.",
    "Lokale ADI-Dateien dieses Profils ebenfalls löschen": "Also delete this profile's local ADI files",
    "Jedes Profil hat eigene Einstellungen, Wavelog-Zugangsdaten, ADI-Dateien und Sync-Metadaten.": "Each profile has its own settings, Wavelog credentials, ADI files and sync metadata.",
    "Das aktive Profil kann nicht gelöscht werden. Bitte zuerst ein anderes Profil aktivieren.": "The active profile cannot be deleted. Activate another profile first.",
    "Ungültige Eingabe": "Invalid input",
})


PHRASES = (
    ("Sprache und Darstellung gelten für alle Stationsprofile.", "Language and appearance apply to all station profiles."),
    ("Synchronisierung läuft", "Synchronization running"),
    ("Synchronisierung abgeschlossen", "Synchronization completed"),
    ("Synchronisierung fehlgeschlagen", "Synchronization failed"),
    ("mögliche Referenz(en) gefunden", "possible reference(s) found"),
    ("mögliche Treffer", "possible matches"),
    ("QSOs", "QSOs"),
    ("Letztes QSO spotten ·", "Spot last QSO ·"),
    ("Ein ZIP sichert alle Logger-Profile, Einstellungen, Sync-Metadaten und ADI-Logbücher.", "A ZIP file backs up all logger profiles, settings, sync metadata and ADI logbooks."),
    ("Gespeicherte Zugangsdaten sind ebenfalls enthalten – das Backup bitte geschützt aufbewahren.", "Saved credentials are included as well – keep the backup protected."),
    ("Schnell, lokal und unabhängig von einer Internetverbindung.", "Fast, local and independent of an internet connection."),
    ("Neues QSO erfassen und sicher lokal speichern.", "Log a new QSO and store it safely on this computer."),
    ("Pileups zügig abarbeiten: Rufzeichen und Enter.", "Work pileups quickly: callsign and Enter."),
    ("Seriennummern und Austauschdaten effizient protokollieren.", "Log serial numbers and exchanges efficiently."),
    ("Lokale QSOs prüfen und Wavelog bewusst manuell synchronisieren.", "Review local QSOs and synchronize with Wavelog manually."),
    ("Das lokale Logbuch auf einen Blick.", "Your local logbook at a glance."),
    ("Funkgerät über das eingebettete Hamlib steuern.", "Control the radio through the bundled Hamlib."),
    ("Live-Spots empfangen, filtern und an den TRX übergeben.", "Receive, filter and tune the radio to live spots."),
    ("QSOs von WSJT-X und kompatiblen Programmen empfangen.", "Receive QSOs from WSJT-X and compatible programs."),
    ("Stationsprofil, Online-Dienste und lokale Daten verwalten.", "Manage station profiles, online services and local data."),
    ("QSOs bleiben lokal, bis du\nmanuell synchronisierst.", "QSOs stay local until you\nsynchronize manually."),
    ("Online-Push:", "Online push:"), ("übertragen", "transferred"),
    ("Fehler · Voll-Sync erforderlich", "errors · full sync required"),
    ("neue QSO(s) zu Wavelog", "new QSO(s) to Wavelog"),
    ("Online-Abfrage optional · Offline-Logging bleibt immer verfügbar.", "Online lookup is optional · Offline logging always remains available."),
    ("CTY.DAT · keine Internetverbindung nötig", "CTY.DAT · no internet connection required"),
    ("Die Änderung wird nach einem Neustart der App aktiv.", "The change becomes active after restarting the app."),
    ("Einstellungen wurden gespeichert.", "Settings have been saved."),
    ("Einstellungen gespeichert", "Settings saved"),
    ("CAT ist ausgeschaltet", "CAT is off"), ("CAT ist gestoppt", "CAT is stopped"),
    ("CAT wird gestartet", "CAT is starting"), ("CAT verbunden", "CAT connected"),
    ("Frequenz:", "Frequency:"), ("Modus:", "Mode:"), ("Verbindung erfolgreich", "Connection successful"),
    ("Verbindung wird geprüft", "Testing connection"), ("Verbindung fehlgeschlagen", "Connection failed"),
    ("Keine Callbook-Daten gefunden", "No callbook data found"),
    ("keine Internetverbindung nötig", "no internet connection required"),
    ("zum Verbinden bitte CAT starten", "start CAT to connect"),
    ("wurde erfolgreich gestartet", "started successfully"),
    ("wurde gespeichert", "was saved"), ("wurde gelöscht", "was deleted"),
)


def translate_text(value: object, language: str) -> str:
    text = "" if value is None else str(value)
    if language != "en" or not text:
        return text
    translated = ENGLISH.get(text)
    if translated is not None:
        return translated
    for german, english in PHRASES:
        if german in text:
            text = text.replace(german, english)
    return text
